PetMarket/petMarket/feedback/urls.py
from django.urls import path, re_path

import feedback.views as feedback

urlpatterns = [
    path('', feedback.feedback),
    path('edit_feedback/<int:feedback_id>/', feedback.editFeedback),
    path('delete_feedback/<int:feedback_id>/', feedback.deleteFeedback),
]

PetMarket/petMarket/feedback/models.py
from django.db import models

class Feedback(models.Model):
    text = models.CharField(max_length=30)
    date_created = models.DateTimeField(auto_now_add=True)
    update = models.BooleanField(default=False)
    update_date = models.DateTimeField(auto_now=True)

PetMarket/petMarket/feedback/forms.py
from django import forms
from .models import Feedback



# class UserForm(forms.Form):
#     name = forms.CharField()
#     age = forms.IntegerField()


class AddFeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['text']   # ЛИБО, ЧТОБЫ ВЗАИМСТВОВАТЬ ВСЕ СРАЗУ ---> '__all__'
        labels = {'text': 'Ваш отзыв:'}
        widgets = {
            'text': forms.Textarea(attrs={'cols': 55, 'rows': 5, 'class': 'form-input'}),
        }

PetMarket/petMarket/feedback/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from feedback.forms import *




def feedback(request):
    if request.method == 'POST':
        text_feedback = request.POST.get('text')
        if len(text_feedback) > 0:
            Feedback.objects.create(text=text_feedback)
            return HttpResponse(f"""
            <h2>Ваш отзыв успешно отправлен</h2>
            <a href=""><button>Вернуться на страницу с отзывами</button></a>
    """)
        else:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


    elif request.method == 'GET':
        results = Feedback.objects.all()
        data = {
            'feedback': results,
            'add_feedback_form': AddFeedbackForm()
        }

        return render(request, 'feedback.html', data)


def editFeedback(request, feedback_id):
    fb = Feedback.objects.get(id=feedback_id)
    if request.method == 'GET':
        data = {
            "feedback": fb,
            'add_feedback_form': AddFeedbackForm()
        }

        return render(request, 'editFeedback.html', data)

    elif request.method == 'POST':
        text_feedback = request.POST.get('text')
        if len(text_feedback) > 0:
            fb.text = text_feedback
            fb.update = True
            fb.save()
            return HttpResponseRedirect('/./feedback/')
        else:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def deleteFeedback(request, feedback_id):
    try:
        Feedback.objects.get(id=feedback_id).delete()
        return HttpResponseRedirect('/./feedback/')
    except Feedback.DoesNotExist:
        return HttpResponseNotFound('''
            <h2>Отзыв не найден.</h2>
            <a href="/./feedback/"><button>Вернуться на страницу с отзывами</button></a>
            ''')

PetMarket/petMarket/feedback/templates/editFeedback.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h2>Ваш текущий отзыв</h2>

<div style="background: lightblue;">
    <p>{{ feedback.text }}</p>
    <p>{{ feedback.date_created }}</p>
</div>

<h2>Отредактировать: </h2>
<form method="POST" novalidate>
    {% csrf_token %}
    {% for field in add_feedback_form %}

        {{ field.label_tag }}

        <div>{{ field }}</div>

        {% if field.errors %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}

    {% endfor %}

    <input id="id_text" type="submit" value="Отправить" class="fb_btn">



</form>
    <script src="{% static 'js/fbscript.js' %}"></script>
</body>
</html>

PetMarket/petMarket/feedback/templates/feedback.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/fbstyle.css' %}" />
</head>
<body>
<h2>Ваш отзыв</h2>

<h3>user_form</h3>
{{ user_form }}

<h3>add_feedback_form</h3>

<form method="POST" novalidate>
    {% csrf_token %}

    {% for field in add_feedback_form %}

        {{ field.label_tag }}

        <div>{{ field }}</div>

        {% if field.errors %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}

    {% endfor %}

    <input id="id_text" type="submit" value="Отправить" class="fb_btn">






</form>





{% comment %}
    {{ add_feedback_form.as_p }}
{% endcomment %}

{% if feedback %}
    <h2>Отзывы</h2>

    {% for item in feedback %}
    <div style="background: lightblue;" id="{{ item.id }}">
        <p>{{ item.text }}</p>
        <p>{{ item.date_created }}
            <span style="color: gray; font-size: 10pt;">
                {% if item.update is True %} (Отредактировано {{ item.update_date }}) {% endif %}
            </span>
        </p>
        <a href="./edit_feedback/{{ item.id }}"><button>редактировать</button></a>
        <a href="./delete_feedback/{{ item.id }}"><button>удалить</button></a>
    </div>
    {% endfor %}
{% endif %}


    <script src="{% static 'js/fbscript.js' %}"></script>
</body>
</html>