XBOX Game Store/xbox_game_store/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from main import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('agreement/', views.agreement, name='agreement'),
    path('privacy/', views.privacy, name='privacy'),
    path('personal-data/', views.personal_data, name='personal-data'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

XBOX Game Store/xbox_game_store/orders/urls.py
from django.urls import path
from orders import views


app_name = 'orders'

urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('increase/<int:product_id>/', views.increase, name='increase'),
    path('decrease/<int:product_id>/', views.decrease, name='decrease'),
]

XBOX Game Store/xbox_game_store/payment/urls.py
from django.urls import path
from payment import views

app_name = 'payment'

urlpatterns = [
    path('gamepass/<int:object_id>/', views.gamepass_pay, name='gamepass'),
    path('cart_pay/<int:cart_id>/', views.cart_pay, name='cart_pay'),
    path('webhook/', views.webhook, name='webhook'),
    path('payment_complete/', views.payment_complete, name='payment_complete'),
]

XBOX Game Store/xbox_game_store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from store import views


app_name = 'store'

urlpatterns = [
    path('', views.catalog, name='catalog'),
    path('gamepass/', views.GamePassPage.as_view(), name='gamepass'),
    path('search/', views.game_search, name='search'),
    path('game/<int:game_id>/', views.ShowGame.as_view(), name='game'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

XBOX Game Store/xbox_game_store/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/',
         PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),

    path('password-reset/',
         PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                   email_template_name="users/password_reset_email.html",
                                   success_url=reverse_lazy("users:password_reset_done")),
         name='password_reset'),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
                                          success_url=reverse_lazy("users:password_reset_complete")),
         name='password_reset_confirm'),

    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

XBOX Game Store/xbox_game_store/xbox_game_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('catalog/', include('store.urls', namespace="store")),
    path('users/', include('users.urls', namespace="users")),
    path('feedback/', include('feedback.urls', namespace="feedback")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('payment/', include('payment.urls', namespace="payment")),
]


handler404 = 'main.views.error_404'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

XBOX Game Store/xbox_game_store/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-input'}))

    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'Email',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }

        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают')
        return cd['password1']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Пользователь с данным email уже зарегистрирован.')
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='Email', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Текущий пароль',
                                   widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label='Новый пароль',
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label='Подтвердите новый пароль',
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))

XBOX Game Store/xbox_game_store/users/views.py
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView
from orders.models import Cart, Purchase
from users.forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('homepage'))


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Регистрация пользователя'}
    success_url = reverse_lazy('users:login')


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Личный кабинет'}

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            cart = Cart.objects.get(user=self.request.user)
        except Cart.DoesNotExist:
            cart = None

        purchases = Purchase.objects.filter(user=self.request.user)
        context['cart'] = cart
        context['purchases'] = purchases
        return context


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change_form.html'
    title = 'Смена пароля'

XBOX Game Store/xbox_game_store/users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/style-login.css' %}">
<link rel="stylesheet" href="{% static 'css/style-navbar-other.css' %}">
{% endblock %}
{% block content %}
{% include 'main/includes/navbar.html' %}

<section class="section-one">
    <div class="container">
    </div>
</section>

<section class="section-two">
    <div class="container">
        <div class="row d-none d-lg-block">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'homepage' %}">Главная</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ title }}</li>
                </ol>
            </nav>
        </div>
    </div>

    <div class="container">
        <div class="row text-white">
            <div class="col-12 xbox-auth d-flex flex-column align-items-center">

                <h1 class="mb-5">{{ title }}</h1>
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}"/>

                    {% for field in form %}
                    <div class="form-group d-flex flex-column align-items-center mb-3">
                        <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% for error in field.errors %}
                        <div class="row">
                            <div class="col-12 xbox-auth d-flex flex-column align-items-center">
                                <p class="mt-2 text-red">
                                    {{ error }}
                                </p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-12 xbox-auth d-flex flex-column align-items-center">
                    {% if form.non_field_errors %}
                        <p class="mt-2 text-red">
                            {% for error in form.non_field_errors %}
                                {{ error }}
                            {% endfor %}
                        </p>
                    {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-12 xbox-auth d-flex flex-column align-items-center mb-4">
                    <div class="form-group text-center mt-4">
                        <button type="submit" class="buy-btn btn btn-success btn-lg">Войти</button>
                    </div>
                    <a href="{% url 'users:password_reset' %}" class="mt-2"><p>Забыли пароль?<p></a>
                </form>
            </div>
        </div>
        <div class="row mb-5 mt-4 text-white">
            <div class="col-12 d-flex flex-column align-items-center">
                <p class="form-group">У вас еще нет аккаунта XBOX Game Store?</p>
                <div class="form-group text-center mt-2">
                    <a href="{% url 'users:register' %}">
                        <button type="submit" class="buy-btn btn btn-success btn-lg">Зарегистрироваться</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

XBOX Game Store/xbox_game_store/users/templates/users/password_change_done.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/style-login.css' %}">
<link rel="stylesheet" href="{% static 'css/style-navbar-other.css' %}">
{% endblock %}
{% block content %}
{% include 'main/includes/navbar.html' %}

<section class="section-one">
    <div class="container">
    </div>
</section>

<section class="section-two text-white">
    <div class="container">
        <div class="row">
            <div class="col-12 xbox-auth d-flex flex-column justify-content-center align-items-center mb-5 register-done-section">
                <h1 class="mb-5">Пароль успешно изменен!</h1>
                <p class="form-group">Вы успешно изменили пароль.</p>
                <p><a href="{% url 'users:profile' %}">Вернуться в профиль</a></p>
            </div>
        </div>
    </div>
</section>

{% endblock %}

XBOX Game Store/xbox_game_store/users/templates/users/password_change_form.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/style-login.css' %}">
<link rel="stylesheet" href="{% static 'css/style-navbar-other.css' %}">
{% endblock %}
{% block content %}
{% include 'main/includes/navbar.html' %}

<section class="section-one">
    <div class="container">
    </div>
</section>

<section class="section-two">
    <div class="container">
        <div class="row d-none d-lg-block">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'homepage' %}">Главная</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ title }}</li>
                </ol>
            </nav>
        </div>
    </div>

    <div class="container">
        <div class="row text-white">
            <div class="col-12 xbox-auth d-flex flex-column align-items-center">

                <h1 class="mb-5">{{ title }}</h1>
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}"/>

                    {% for field in form %}
                    <div class="form-group d-flex flex-column align-items-center mb-3">
                        <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% for error in field.errors %}
                        <div class="row">
                            <div class="col-12 xbox-auth d-flex flex-column align-items-center">
                                <p class="mt-2 text-red">
                                    {{ error }}
                                </p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% endfor %}
                </div>
        </div>
        <div class="row">
            <div class="col-12 xbox-auth d-flex flex-column align-items-center">
                    {% if form.non_field_errors %}
                        <p class="mt-2 text-red">
                            {% for error in form.non_field_errors %}
                                {{ error }}
                            {% endfor %}
                        </p>
                    {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-12 xbox-auth d-flex flex-column align-items-center mb-4">
                    <div class="form-group text-center mt-4">
                        <button type="submit" class="buy-btn btn btn-success btn-lg">Сменить пароль</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

XBOX Game Store/xbox_game_store/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/style-login.css' %}">
<link rel="stylesheet" href="{% static 'css/style-navbar-other.css' %}">
{% endblock %}
{% block content %}
{% include 'main/includes/navbar.html' %}

<section class="section-one">
    <div class="container">
    </div>
</section>

<section class="section-two text-white">
    <div class="container">
        <div class="row">
            <div class="col-12 xbox-auth d-flex flex-column justify-content-center align-items-center mb-5 register-done-section">
                <h1 class="mb-5">Пароль успешно изменен!</h1>
                <p class="form-group">Поздравляем! Вы успешно изменили пароль своего аккаунта.</p>
                <p>Воспользуйтесь новым паролем для того, чтобы <a href="{% url 'users:login' %}">войти в систему</a>.</p>
            </div>
        </div>
    </div>
</section>

{% endblock %}

XBOX Game Store/xbox_game_store/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/style-login.css' %}">
<link rel="stylesheet" href="{% static 'css/style-navbar-other.css' %}">
{% endblock %}
{% block content %}
{% include 'main/includes/navbar.html' %}

<section class="section-one">
    <div class="container">
    </div>
</section>

<section class="section-two">
    <div class="container">
        <div class="row d-none d-lg-block">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'homepage' %}">Главная</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ title }}</li>
                </ol>
            </nav>
        </div>
    </div>

    <div class="container">
        <div class="row text-white">
            <div class="col-12 xbox-auth d-flex flex-column align-items-center">
                <h1 class="mb-5">{{ title }}</h1>
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}" />

                    {% for field in form %}
                    <div class="form-group d-flex flex-column align-items-center mb-3">
                        <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% for error in field.errors %}
                        <div class="row">
                            <div class="col-12 xbox-auth d-flex flex-column align-items-center">
                                <p class="mt-2 text-red">
                                    {{ error }}
                                </p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% endfor %}

                    <div class="col-12 xbox-auth d-flex flex-column align-items-center">
                        {% if form.non_field_errors %}
                        <p class="mt-2 text-red">
                            {% for error in form.non_field_errors %}
                            {{ error }}
                            {% endfor %}
                        </p>
                        {% endif %}
                    </div>

                    <div class="col-12 xbox-auth d-flex flex-column align-items-center mb-4">
                        <div class="form-group text-center mt-4">
                            <button type="submit" class="buy-btn btn btn-success">Изменить пароль</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

XBOX Game Store/xbox_game_store/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

XBOX Game Store/xbox_game_store/users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% load truncatechars %}
{% load class_name %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/style-profile.css' %}">
<link rel="stylesheet" href="{% static 'css/style-navbar-other.css' %}">
{% endblock %}
{% block content %}
{% include 'main/includes/navbar.html' %}

<section class="section-one">
    <div class="container">
    </div>
</section>

<section class="section-two">
    <div class="container">
        <div class="row d-none d-lg-block">
            <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'homepage' %}">Главная</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ title }}</li>
                </ol>
            </nav>
        </div>
        <h1 class="mt-5 text-white">{{ title }}</h1>
    </div>
</section>

<section class="section-three">
    <div class="container">
        <div class="row text-white">
            <div id="cart-detail" class="col-xl-8 col-12 table-responsive">
                <h2 class="pb-4">Корзина <span><img src="{% static 'img/icon/cart2.png' %}" alt="" width="40"></span></h2>
                {% if cart.items.exists %}
                <table class="table table-dark">
                    <thead>
                        <tr class="table-active">
                            <th>
                                НАИМЕНОВАНИЕ
                            </th>
                            <th class="dnone">
                                ЦЕНА
                            </th>
                            <th>
                                КОЛИЧЕСТВО
                            </th>
                            <th class="dnone">
                                СТОИМОСТЬ
                            </th>
                            <th class="dnone">

                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart.items.all %}
                        <tr>
                            <td>
                                <a href="{% url 'store:game' item.product.id %}">
                                    <img src="{{ item.product.banner_image.url }}" alt="{{ item.product.title }}" width="70" class="dnone">
                                    <span class="game-title">{{ item.product.title|truncatechars:22 }}</span>
                                </a>
                            </td>
                            <td class="dnone">
                                {{ item.product.price }} ₽
                            </td>
                            <td>
                                <a href="{% url 'orders:decrease' item.product.id %}" class="btn-container">
                                    <button type="button" class="btn btn-dark">-</button>
                                </a>
                                <span class="quantity">{{ item.quantity }}</span>
                                <a href="{% url 'orders:increase' item.product.id %}" class="btn-container">
                                    <button type="button" class="btn btn-dark">+</button>
                                </a>
                            </td>
                            <td class="dnone">
                                {{ item.get_total_price }} ₽
                            </td>
                            <td class="dnone">
                                <form action="{% url 'orders:remove_from_cart' item.product.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn-close" aria-label="Удалить"></button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="col d-flex flex-column justify-content-end align-items-start align-items-lg-end">
                    <p class="small-text">Итого: <span class="big-text">{{ cart.get_total_price }}₽</span></p>
                    <a href="{% url 'payment:cart_pay' cart.id %}" title="...">
                        <button type="button" class="btn btn-success btn-lg">
                            ОФОРМИТЬ
                        </button>
                    </a>
                </div>

                {% else %}
                <h5 class="need-margin">Ваша корзина пока пуста 😞</h5>
                <p class="need-margin">Предлагаем перейти в <a href="{% url 'store:catalog' %}">каталог</a> и ознакомиться с нашим списком игр. <br>Гарантируем, он не оставит вас без внимания!</p>
                {% endif %}


                {% if purchases.exists %}
                <h2 class="pt-5">Ваши покупки ({{ purchases.count }}):</h2>
                {% for purchase in purchases %}
                <hr>
                <table class="table table-dark caption-top purchase">
                    <caption class="text-white small-text">{{ purchase.created_at }}. Сумма покупки: <span class="big-text">{{ purchase.get_total_price }}₽</span></caption>
                    <thead>
                        <tr class="table-active">
                            <th width="100">
                                НАИМЕНОВАНИЕ
                            </th>
                            <th class="dnone" width="100">
                                ЦЕНА
                            </th>
                            <th width="100">
                                КОЛИЧЕСТВО
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in purchase.items.all %}
                        <tr>
                            <td>
                                {% if item.content_object|class_name == 'Game' %}
                                <a href="{% url 'store:game' item.content_object.id %}">
                                    <span class="game-title">{{ item.content_object.title|truncatechars:30 }}</span>
                                </a>
                                {% elif item.content_object|class_name == 'GamePass' %}
                                <a href="{% url 'store:gamepass' %}">
                                    <span class="game-title">Game Pass {{ item.content_object.title|truncatechars:30 }}</span>
                                </a>
                                {% endif %}
                            </td>
                            <td class="dnone">
                                {{ item.content_object.price }}₽
                            </td>
                            <td>
                                {{ item.quantity }} шт.
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% endfor %}
                <hr>
                {% endif %}
            </div>




            <div class="col-xl-4 col-12 xbox-auth d-flex flex-column align-items-center">
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}" />

                    {% for field in form %}
                    <div class="form-group d-flex flex-column align-items-center mb-3">
                        <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% for error in field.errors %}
                        <div class="row">
                            <div class="col-12 xbox-auth d-flex flex-column align-items-center">
                                <p class="mt-2 text-red">
                                    {{ error }}
                                </p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% endfor %}
                    {% if form.non_field_errors %}
                <p class="mt-2 text-red">
                    {% for error in form.non_field_errors %}
                    {{ error }}
                    {% endfor %}
                </p>
                {% endif %}
                <div class="form-group text-center mt-4">
                    <button type="submit" class="buy-btn btn btn-success btn-lg">Изменить</button>
                </div>
                <div class="form-group text-center mt-4">
                    <a href="{% url 'users:password_change' %}">
                        <p>Сменить пароль<p>
                    </a>
                </div>
                </form>
                <div class="form-group text-center mt-4">
                    <a href="{% url 'users:logout' %}"><button type="submit"
                            class="buy-btn btn btn-success btn-lg">Выйти из профиля</button></a>
                </div>
            </div>
        </div>
    </div>
</section>




{% endblock %}