XBOX Game Store/xbox_game_store/feedback/urls.py
from django.urls import path
from . import views

app_name = 'feedback'

urlpatterns = [
    path('', views.feedbacks, name='main'),
]

XBOX Game Store/xbox_game_store/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from main import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('agreement/', views.agreement, name='agreement'),
    path('privacy/', views.privacy, name='privacy'),
    path('personal-data/', views.personal_data, name='personal-data'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

XBOX Game Store/xbox_game_store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from store import views


app_name = 'store'

urlpatterns = [
    path('', views.catalog, name='catalog'),
    path('gamepass/', views.GamePassPage.as_view(), name='gamepass'),
    path('search/', views.game_search, name='search'),
    path('game/<int:game_id>/', views.ShowGame.as_view(), name='game'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

XBOX Game Store/xbox_game_store/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/',
         PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),

    path('password-reset/',
         PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                   email_template_name="users/password_reset_email.html",
                                   success_url=reverse_lazy("users:password_reset_done")),
         name='password_reset'),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
                                          success_url=reverse_lazy("users:password_reset_complete")),
         name='password_reset_confirm'),

    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

XBOX Game Store/xbox_game_store/xbox_game_store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('catalog/', include('store.urls', namespace="store")),
    path('users/', include('users.urls', namespace="users")),
    path('feedback/', include('feedback.urls', namespace="feedback")),
    path('orders/', include('orders.urls', namespace="orders")),
    path('payment/', include('payment.urls', namespace="payment")),
]


handler404 = 'main.views.error_404'


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

XBOX Game Store/xbox_game_store/main/models.py
from django.db import models


class News(models.Model):
    image = models.ImageField(upload_to='news_images/')
    title = models.CharField(max_length=200)
    content = models.TextField()

    def __str__(self):
        return self.title

XBOX Game Store/xbox_game_store/main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from main.models import News
from store.models import Game, CarouselItem, GamePass
import random


def get_random_games(count: int):
    game_count = Game.objects.count()
    if game_count <= count:
        games = Game.objects.all()
    else:
        game_ids = set()
        while len(game_ids) < count:
            random_id = random.randint(1, game_count)
            if Game.objects.filter(id=random_id).exists():
                game_ids.add(random_id)
        games = Game.objects.filter(id__in=game_ids)
    return games


class HomePage(TemplateView):
    template_name = 'main/index.html'
    extra_context = {
        'games': get_random_games(8),
        'carousel': CarouselItem.objects.all(),
        'news': News.objects.order_by('-id')[:2],
        'gamepass': GamePass.objects.all(),
        'title': 'Главная страница',
        'current_page': 'homepage',
    }


class AboutPage(TemplateView):
    template_name = 'main/about.html'
    extra_context = {
        'title': 'Гарантии',
        'current_page': 'about',
    }


def agreement(request):
    data = {
        'title': 'Пользовательское соглашение'
    }
    return render(request, 'main/agreement.html', data)


def privacy(request):
    data = {
        'title': 'Политика конфиденциальности'
    }
    return render(request, 'main/privacy.html', data)


def personal_data(request):
    data = {
        'title': 'Согласие на обработку персональных данных'
    }
    return render(request, 'main/personal-data.html', data)


def error_404(request, exception):
    return render(request, 'main/404.html', status=404)

XBOX Game Store/xbox_game_store/main/templates/main/includes/navbar.html
{% load static %}

    <nav class="navbar navbar-expand-lg fixed-top">
        <div class="container-fluid">
            <img src="{% static 'img/logo.png' %}" class="navbar-brand me-auto img-fluid" alt="" width="180">
            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"
                aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header" data-bs-theme="dark">
                    <img src="{% static 'img/logo.png' %}" class="img-fluid" alt="" width="200">
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Закрыть"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
                        <li class="nav-item">
                            <a class="nav-link mx-lg-2 {% if current_page == 'homepage' %}active{% endif %}" aria-current="page" href="{% url 'homepage' %}">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mx-lg-2 {% if current_page == 'catalog' %}active{% endif %}" href="{% url 'store:catalog' %}">Каталог</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mx-lg-2 {% if current_page == 'about' %}active{% endif %}" href="{% url 'about' %}">Гарантии</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mx-lg-2 {% if current_page == 'feedback' %}active{% endif %}" href="{% url 'feedback:main' %}">Отзывы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mx-lg-2 {% if current_page == 'search' %}active{% endif %}" href="{% url 'store:search' %}"><img src="{% static 'img/magnifier.png' %}" alt="" width="20">Поиск игр</a>
                        </li>
                    </ul>
                </div>
            </div>
            {% if user.is_authenticated %}
            <a href="{% url 'users:profile' %}" class="login-button text-white">
                <img src="{% static 'img/icon/cabinet.png' %}" alt="" width="30">
                {% if cart.items.exists %}
                <span class="position-absolute top-10 translate-middle badge rounded-pill bg-warning">
                    <img src="{% static 'img/icon/cart.png' %}" alt="" width="20">
                    <span class="visually-hidden">Корзина</span>
                </span>
                {% endif %}
            </a>
            {% else %}
            <a href="{% url 'users:login' %}" class="login-button text-white">
                <img src="{% static 'img/icon/entrance.png' %}" alt="" width="30">
            </a>
            {% endif %}
            <button class="navbar-toggler pe-0" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Переключить навигацию">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>